head()   =   read 5 line top
head(x)  =   read x line top
tail()   =   read 5 line down
tail(x)  =   read x line down
sample() =   1 sample
sample(x)=   x sample
dascribe()=  see stat
shape    =   (row,column)
column   =   check column
values   =  read array

In [7]:
import pandas as pd
df = pd.read_excel("dataupdate.xlsx")

In [8]:
df

          Day  Temperature  WindSpeed    Event
0  2020-12-01           30          9  แดดร้อน
1  2020-12-02           28          8   เมฆมาก
2  2020-12-03           27          4     ฝนตก
3  2020-12-04           19          3  แดดร้อน
4  2020-12-05           20          5   เมฆมาก
5  2020-12-06           25          6     ฝนตก
6  2020-12-07           36          4     ฝนตก
7  2020-12-08           28          6     ฝนตก
8  2020-12-09           17          5   เมฆมาก
9  2020-12-10           24          6  แดดร้อน
10 2020-12-11           26          4     ฝนตก
11 2020-12-12           27          9  แดดร้อน
12 2020-12-13           30          2  แดดร้อน
13 2020-12-14           31          5   เมฆมาก
14 2020-12-15           28          4  แดดร้อน
15 2020-12-16           27          7  แดดร้อน
16 2020-12-17           20          8     ฝนตก
17 2020-12-18           18          5     ฝนตก
18 2020-12-19           25          7  แดดร้อน
19 2020-12-20           28          4   เมฆมาก
20 2020-12-21           25          5   เมฆมาก
21 2020-12-22           38          2   เมฆมาก
22 2020-12-23           34          3     ฝนตก
23 2020-12-24           29          4     ฝนตก
24 2020-12-25           34          5  แดดร้อน
25 2020-12-26           25          8     ฝนตก
26 2020-12-27           28          9   เมฆมาก
27 2020-12-28           30          2   เมฆมาก
28 2020-12-29           31          1     ฝนตก
29 2020-12-30           35          2     ฝนตก

In [11]:
# x line frist
df.head(7)

         Day  Temperature  WindSpeed    Event
0 2020-12-01           30          9  แดดร้อน
1 2020-12-02           28          8   เมฆมาก
2 2020-12-03           27          4     ฝนตก
3 2020-12-04           19          3  แดดร้อน
4 2020-12-05           20          5   เมฆมาก
5 2020-12-06           25          6     ฝนตก
6 2020-12-07           36          4     ฝนตก

In [12]:
# x line last
df.tail(6)

          Day  Temperature  WindSpeed    Event
24 2020-12-25           34          5  แดดร้อน
25 2020-12-26           25          8     ฝนตก
26 2020-12-27           28          9   เมฆมาก
27 2020-12-28           30          2   เมฆมาก
28 2020-12-29           31          1     ฝนตก
29 2020-12-30           35          2     ฝนตก

In [14]:
# random
df.sample(3)

          Day  Temperature  WindSpeed    Event
21 2020-12-22           38          2   เมฆมาก
3  2020-12-04           19          3  แดดร้อน
12 2020-12-13           30          2  แดดร้อน

In [16]:
df.describe()

       Temperature  WindSpeed
count    30.000000  30.000000
mean     27.433333   5.066667
std       5.237026   2.288402
min      17.000000   1.000000
25%      25.000000   4.000000
50%      28.000000   5.000000
75%      30.000000   6.750000
max      38.000000   9.000000

In [18]:
df.shape

(30, 4)

In [19]:
df.columns

Index(['Day', 'Temperature', 'WindSpeed', 'Event'], dtype='object')

In [20]:
df.values

array([[Timestamp('2020-12-01 00:00:00'), 30, 9, 'แดดร้อน'],
       [Timestamp('2020-12-02 00:00:00'), 28, 8, 'เมฆมาก'],
       [Timestamp('2020-12-03 00:00:00'), 27, 4, 'ฝนตก'],
       [Timestamp('2020-12-04 00:00:00'), 19, 3, 'แดดร้อน'],
       [Timestamp('2020-12-05 00:00:00'), 20, 5, 'เมฆมาก'],
       [Timestamp('2020-12-06 00:00:00'), 25, 6, 'ฝนตก'],
       [Timestamp('2020-12-07 00:00:00'), 36, 4, 'ฝนตก'],
       [Timestamp('2020-12-08 00:00:00'), 28, 6, 'ฝนตก'],
       [Timestamp('2020-12-09 00:00:00'), 17, 5, 'เมฆมาก'],
       [Timestamp('2020-12-10 00:00:00'), 24, 6, 'แดดร้อน'],
       [Timestamp('2020-12-11 00:00:00'), 26, 4, 'ฝนตก'],
       [Timestamp('2020-12-12 00:00:00'), 27, 9, 'แดดร้อน'],
       [Timestamp('2020-12-13 00:00:00'), 30, 2, 'แดดร้อน'],
       [Timestamp('2020-12-14 00:00:00'), 31, 5, 'เมฆมาก'],
       [Timestamp('2020-12-15 00:00:00'), 28, 4, 'แดดร้อน'],
       [Timestamp('2020-12-16 00:00:00'), 27, 7, 'แดดร้อน'],
       [Timestamp('2020-12-17 00:00:00'), 20, 8, 'ฝนตก'],
       [Timestamp('2020-12-18 00:00:00'), 18, 5, 'ฝนตก'],
       [Timestamp('2020-12-19 00:00:00'), 25, 7, 'แดดร้อน'],
       [Timestamp('2020-12-20 00:00:00'), 28, 4, 'เมฆมาก'],
       [Timestamp('2020-12-21 00:00:00'), 25, 5, 'เมฆมาก'],
       [Timestamp('2020-12-22 00:00:00'), 38, 2, 'เมฆมาก'],
       [Timestamp('2020-12-23 00:00:00'), 34, 3, 'ฝนตก'],
       [Timestamp('2020-12-24 00:00:00'), 29, 4, 'ฝนตก'],
       [Timestamp('2020-12-25 00:00:00'), 34, 5, 'แดดร้อน'],
       [Timestamp('2020-12-26 00:00:00'), 25, 8, 'ฝนตก'],
       [Timestamp('2020-12-27 00:00:00'), 28, 9, 'เมฆมาก'],
       [Timestamp('2020-12-28 00:00:00'), 30, 2, 'เมฆมาก'],
       [Timestamp('2020-12-29 00:00:00'), 31, 1, 'ฝนตก'],
       [Timestamp('2020-12-30 00:00:00'), 35, 2, 'ฝนตก']], dtype=object)

mean()   =   avg
max()    =   max value
min()    =   min value
count()  =   how much value
std()    =   SD
sum()    =   summation